# Generated by Django 4.1 on 2024-10-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_apiproducto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apiproducto',
            table='api_producto',
        ),
    ]
