# Generated by Django 4.1 on 2024-10-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_apiproducto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apiproducto',
            table='productos',
        ),
    ]
